services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=generativeAIDB'
      - 'MONGO_INITDB_ROOT_PASSWORD=123456'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=123456'
      - 'RABBITMQ_DEFAULT_USER=root'
    ports:
      - '5673:5673'
      - '15673:15673'
